version: '3'
services:
  jenkins:
    build: .
    #    ports:
    #      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lololo
    environment:
      - VIRTUAL_HOST=jenkins.dima.interns.computerstein.net
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=jenkins.dima.interns.computerstein.net
      - LETSENCRYPT_EMAIL=mr.paukov@gmail.com

networks:
  lololo:
    external: true
